apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: astroshop
    repo: oci://europe-docker.pkg.dev/dynatrace-demoability/helm
    version: 0.3.5
    releaseName: astroshop
    additionalValuesFiles:
      - values.yaml
      - values.local.yaml

namespace: astroshop

resources:
  - ./namespace.yaml
  - ./ingress-class-params.yaml
  - ./ingress-class.yaml
  - ./ingress.yaml

components:
  - ../components/ownership-labels
  - ../components/flagd-config
  - ../components/flag-admin-ui

patches:
  - target:
      version: v1
      kind: Deployment
      name: image-provider
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/1/ports/0/name
        value: metrics
